version: '3.8'

services:
  microservicio-dashboard-reportes:
    image: matiasjara1901244/proyecto-gps-microserviciodashboardreportes:latest
    container_name: microservicio-dashboard-reportes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d1osq23uibrs73d4hrig-a.oregon-postgres.render.com:5432/postgresss_33h5?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgresss_33h5_user
      SPRING_DATASOURCE_PASSWORD: 8lsWOLx1Ub4jFnMKJFrnTXZTBcJ2VgbH
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true